#if 1
APPNAME "*fsel_pshell.width:			400",
APPNAME "*fsel_pshell.height:			400",
APPNAME "*fsel_pshell.x:			200",
APPNAME "*fsel_pshell.y:			80",
APPNAME "*fsel_form.xLayout:			5 100 5 50% 5 50% 5 100 5",
APPNAME "*fsel_form.yLayout:			35 5 25 5 25 5 100% 5 22 5 32",
APPNAME "*fsel_topframe.gridWidth:		9",
APPNAME "*fsel_topframe.shadowWidth:		1",
APPNAME "*fsel_topbox.borderWidth:		0",
APPNAME "*fsel_formatlabel.gridx:		1",
APPNAME "*fsel_formatlabel.gridy:		2",
APPNAME "*fsel_formatbutton.gridx:		3",
APPNAME "*fsel_formatbutton.gridy:		2",
APPNAME "*fsel_formatbutton.gridWidth:		5",
APPNAME "*fsel_dirlabel.gridx:			1",
APPNAME "*fsel_dirlabel.gridy:			4",
APPNAME "*fsel_dirbutton.gridx:			3",
APPNAME "*fsel_dirbutton.gridy:			4",
APPNAME "*fsel_dirbutton.gridWidth:		5",
APPNAME "*fsel_dirframe.gridx:			1",
APPNAME "*fsel_dirframe.gridy:			6",
APPNAME "*fsel_dirframe.gridWidth:		3",
APPNAME "*fsel_dirframe.shadowType:		Groove",
APPNAME "*fsel_dirframe.marginWidth:		2",
APPNAME "*fsel_dirframe.marginHeight:		2",
APPNAME "*fsel_dirframe.allowResize:		False",
APPNAME "*fsel_dirviewport.forceBars:		True",
APPNAME "*fsel_dirviewport.borderWidth:		0",
#endif
APPNAME "*fsel_dirlist.background:		white",
#if 1
APPNAME "*fsel_fileframe.gridx:			5",
APPNAME "*fsel_fileframe.gridy:			6",
APPNAME "*fsel_fileframe.gridWidth:		3",
APPNAME "*fsel_fileframe.shadowType:		Groove",
APPNAME "*fsel_fileframe.marginWidth:		2",
APPNAME "*fsel_fileframe.marginHeight:		2",
APPNAME "*fsel_fileframe.allowResize:		False",
APPNAME "*fsel_fileviewport.forceBars:		True",
APPNAME "*fsel_fileviewport.borderWidth:	0",
#endif
APPNAME "*fsel_filelist.background:		white",
#if 1
APPNAME "*fsel_filelabel.gridx:			1",
APPNAME "*fsel_filelabel.gridy:			8",
APPNAME "*fsel_textframe.gridx:			3",
APPNAME "*fsel_textframe.gridy:			8",
APPNAME "*fsel_textframe.gridWidth:		5",
APPNAME "*fsel_textframe.allowResize:		False",
APPNAME "*fsel_textframe.shadowType:		Lowered",
APPNAME "*fsel_textframe.shadowWidth:		1",
APPNAME "*fsel_bottomframe.gridy:		10",
APPNAME "*fsel_bottomframe.gridWidth:		9",
APPNAME "*fsel_bottomframe.shadowWidth:		1",
APPNAME "*fsel_bottombox.borderWidth:		0",
APPNAME "*fsel_filetext.borderWidth:		0",
#endif
APPNAME "*fsel_filetext.translations: #override\\n\
	<Key>Return:		fsel-done()\\n\
	<Key>Escape:		fsel-cancel()",
#if 1
APPNAME "*fsel_formatbutton.justify:		Left",
APPNAME "*fsel_formatbutton.shadowWidth:	1",
APPNAME "*fsel_dirbutton.justify:		Left",
APPNAME "*fsel_dirbutton.shadowWidth:		1",
#endif
